### ISSUE TITLE
What's the benefit of using react-native-listitem?

### ISSUE THREAD

**Issue by hokster7** [dancormier/react-native-listitem#13]
After reading the README, I still wasn't clear why listitem was needed given that any component could be used together with `ListView`.

Is it just simply because `ListView` doesn't touches of individual rows unless you use `TouchableHighlight` explicitly?

**Comment by dancormier** [comment]
While attempting to build native-looking listitems for an app, I had to do lots of comparing of iOS listitems styling to get it exactly correct. _I built react-native-listitem to act as a quick default for iOS-native styling of a listitem_ (iOS listitem default font-size, weight, margins, border, et cetera).
I'll clarify the README to explain this.

**Comment by dancormier** [comment]
README updated 4112e065e0c5ee3c20dd3c455433f6ee4835c3c5
