### ISSUE TITLE
Pass props to custom child component

### ISSUE THREAD

**Issue by krishpop** [dancormier/react-native-listitem#16]
It would be nice to have the option to pass props to the child component, in case we wanted to use a complex element that you want to pass other props to.

**Comment by dancormier** [comment]
Hey @krishpop,
The children passed to Listitem component can be any component with any props. If you're changing props, you'd just update the child component.
If I'm misinterpreting your suggestion, let me know.

**Comment by krishpop** [comment]
Hey! My mistake, I hadn't thought of that. Thanks!

**Comment by dancormier** [comment]
My pleasure :+1:
