### ISSUE TITLE
Verify that default text style and padding matches iOS

### ISSUE THREAD

**Issue by dancormier** [dancormier/react-native-listitem#6]

**Comment by jacobp100** [comment]
The separators between items excluding the very top and bottom should start on the left at the same left as the text. Look in iOS settings for what I mean.

**Comment by dancormier** [comment]
You are correct, sir. This has been corrected in 7c310797259b89e82d8377d979f4c43963e54fba.

**Comment by jacobp100** [comment]
Also, if the user changes the font size in the accessibility settings, does it adjust?

**Comment by dancormier** [comment]
At the moment, accessibility changes do not affect the component. Moved to #9.
